spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

server:
  port: 8760

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8760/eureka
  server:
    wait-time-in-ms-when-sync-empty: 3000

#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: 12345d

logging:
  level:
    com:
      netflix:
        eureka : OFF
        discovery : OFF